#!/usr/bin/env python3
"""Derive the skill/agent/slash-command inventory and rewrite README.md's
generated block.

Every count and table in README's "## Inventory" section is DERIVED here from
the compose recipes themselves — never hand-typed. A recipe added, removed, or
renamed under .shared-llm/compose/{skills,agents,slash-commands}/ changes what
the next `just inventory` run writes; nothing downstream has to remember to
update a count by hand. This is the durable fix for count drift (a hand-typed
"18 generic agents" going stale the moment a 19th agent is added) — the
generator, not the numbers it prints, is the artifact that must stay correct.

Reuses tools/harness.py's `load_compose_yaml` (the same fail-loud recipe
validation the real composer runs) and `read_file` (the same fail-loud file
read) — one source of truth for what a valid recipe looks like, not a second
YAML parser with its own opinions.

Idempotent: re-running against unchanged recipes leaves README.md
byte-identical (zero diff).

Usage:
    python3 tools/gen_inventory.py     # rewrite README.md's inventory block in place
"""

from __future__ import annotations

from pathlib import Path
import sys

import harness  # tools/harness.py, same dir — sys.path[0] resolves it when run as a script

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED = REPO_ROOT / ".shared-llm"
README = REPO_ROOT / "README.md"

BEGIN_MARKER = "<!-- BEGIN:inventory -->"
END_MARKER = "<!-- END:inventory -->"
GENERATED_NOTICE = (
    "<!-- GENERATED by tools/gen_inventory.py (`just inventory`) — do not hand-edit. "
    "Edit a compose recipe under .shared-llm/compose/{skills,agents,slash-commands}/ "
    "and re-run. -->"
)

# One row per inventory section: (heading label, recipe dir, blurb shown under the heading).
# The recipe dir is the ONLY thing that decides membership/count — adding a yaml here
# shows up next run, removing one drops out, with no hand-maintained list anywhere.
CATEGORIES: list[tuple[str, Path, str]] = [
    (
        "Skills",
        SHARED / "compose" / "skills",
        "Per-repo skills — composed into a destination's `.claude/skills/<name>/SKILL.md` "
        "from a general layer plus an optional `this_repo` overlay.",
    ),
    (
        "Generic agents",
        SHARED / "compose" / "agents",
        "Brand-free agent personas the global step copies into `~/.claude/agents/` and "
        "`~/.pi/agents/`. Adopt them as-is — they contain no project-specific references.",
    ),
    (
        "Slash-command skills",
        SHARED / "compose" / "slash-commands",
        "Routed slash-command skills — `do-*` symlinks to Pi only, `cc-*` stays Claude-only, "
        "everything else ships to both. Composed into a destination's "
        "`.claude/skills/<name>/SKILL.md`.",
    ),
]

MAX_DESC_LEN = 100


def discover_recipes(recipe_dir: Path) -> list[Path]:
    """Every *.yaml / *.yml recipe under a compose subdir, sorted for determinism.
    Mirrors harness.py's own Composer.discover()."""
    if not recipe_dir.is_dir():
        print(f"error: compose directory not found: {recipe_dir}", file=sys.stderr)
        sys.exit(1)
    yamls = sorted(recipe_dir.rglob("*.yaml"))
    yamls += sorted(recipe_dir.rglob("*.yml"))
    return yamls


def summarize(text: str, max_len: int = MAX_DESC_LEN) -> str:
    """First paragraph of a description, collapsed to one line and capped at
    max_len (word-boundary truncation with an ellipsis). Mechanical and
    reproducible — never a hand-curated summary, so it can't drift from the
    recipe it was derived from."""
    first_block = text.strip().split("\n\n", 1)[0]
    line = " ".join(first_block.split())
    if len(line) <= max_len:
        return line
    return line[:max_len].rsplit(" ", 1)[0] + "…"


def escape_cell(text: str) -> str:
    """Escape characters that would break a markdown table cell."""
    return text.replace("|", "\\|")


def load_entries(recipe_dir: Path) -> list[tuple[str, str]]:
    """(name, one-line description) for every recipe under recipe_dir, sorted by name."""
    entries: list[tuple[str, str]] = []
    for yaml_path in discover_recipes(recipe_dir):
        data = harness.load_compose_yaml(yaml_path)
        name = data.get("name")
        if not name:
            print(f"error: {yaml_path} has no 'name' field (required for the inventory)", file=sys.stderr)
            sys.exit(1)
        desc_rel = data.get("description")
        if not isinstance(desc_rel, str):
            print(f"error: {yaml_path} has no 'description' field (required for the inventory)", file=sys.stderr)
            sys.exit(1)
        desc_text = harness.read_file(REPO_ROOT / desc_rel)
        entries.append((name, summarize(desc_text)))
    entries.sort(key=lambda e: e[0])
    return entries


def render_table(entries: list[tuple[str, str]]) -> str:
    lines = ["| Name | Description |", "| --- | --- |"]
    for name, desc in entries:
        lines.append(f"| `{name}` | {escape_cell(desc)} |")
    return "\n".join(lines)


def render_block() -> str:
    sections = []
    for label, recipe_dir, blurb in CATEGORIES:
        entries = load_entries(recipe_dir)
        sections.append(f"### {label} ({len(entries)})\n\n{blurb}\n\n{render_table(entries)}")
    body = "\n\n".join(sections)
    return f"{BEGIN_MARKER}\n{GENERATED_NOTICE}\n\n{body}\n{END_MARKER}"


def rewrite_readme() -> bool:
    """Replace the text between the markers with fresh content. Returns True if
    the file changed. Fails loud if the markers are missing, duplicated, or
    reversed — this never guesses where the block belongs."""
    if not README.is_file():
        print(f"error: file not found: {README}", file=sys.stderr)
        sys.exit(1)
    original = README.read_text()

    begin_count = original.count(BEGIN_MARKER)
    end_count = original.count(END_MARKER)
    if begin_count != 1 or end_count != 1:
        print(
            f"error: expected exactly one {BEGIN_MARKER!r} and one {END_MARKER!r} "
            f"in {README}, found {begin_count} and {end_count}",
            file=sys.stderr,
        )
        sys.exit(1)

    start = original.index(BEGIN_MARKER)
    end = original.index(END_MARKER) + len(END_MARKER)
    if start > end:
        print(f"error: {END_MARKER!r} appears before {BEGIN_MARKER!r} in {README}", file=sys.stderr)
        sys.exit(1)

    updated = original[:start] + render_block() + original[end:]
    changed = updated != original
    if changed:
        README.write_text(updated)
    return changed


def main() -> None:
    changed = rewrite_readme()
    if changed:
        print(f"inventory: {README} updated.")
    else:
        print(f"inventory: {README} already up to date.")


if __name__ == "__main__":
    main()
